version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: parking_lot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # This DATABASE_URL uses the service name 'db' and the internal container port '5432'
      DATABASE_URL: postgres://postgres:pass123@db:5432/parking_lot
    depends_on:
      - db

volumes:
  db_data: