# Generated by Django 4.1 on 2022-08-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Area Name"
                    ),
                ),
                ("capacity", models.IntegerField(default=0, verbose_name="Capacity")),
            ],
            options={"verbose_name_plural": "Areas"},
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("FOUR-SMALL", "Four-Small"),
                            ("FOUR-LARGE", "Four-Large"),
                        ],
                        default="Four-Small",
                        max_length=150,
                        verbose_name="Parking Size",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("OCCUPIED", "Occupied"),
                            ("IN REPAIR", "In Repair"),
                        ],
                        default="Empty",
                        max_length=150,
                        verbose_name="Status",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_parkings",
                        to="api.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Parking"},
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entry Time"),
                ),
                ("exit_time", models.DateTimeField(verbose_name="Exit Time")),
                ("price", models.FloatField(default=0, verbose_name="Parking Price")),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_ticket",
                        to="api.parking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_user_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Ticket"},
        ),
    ]
