# Generated by Django 5.1.4 on 2025-06-11 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="status",
        ),
        migrations.AddField(
            model_name="parking",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Parking Description"
            ),
        ),
        migrations.AddField(
            model_name="parking",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Parking Location"
            ),
        ),
        migrations.AddField(
            model_name="parking",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Parking Name"
            ),
        ),
        migrations.CreateModel(
            name="ParkingSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("floor", models.IntegerField(default=0, verbose_name="Floor Number")),
                (
                    "parking_type",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("FOUR-SMALL", "Four-Small"),
                            ("FOUR-LARGE", "Four-Large"),
                        ],
                        default="FOUR-SMALL",
                        max_length=50,
                        verbose_name="Parking Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Section Name",
                    ),
                ),
                ("capacity", models.IntegerField(default=0, verbose_name="Capacity")),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_section",
                        to="api.parking",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parking Section",
            },
        ),
        migrations.CreateModel(
            name="ParkingPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="HOURLY",
                        max_length=50,
                        verbose_name="Parking Type",
                    ),
                ),
                ("price", models.FloatField(default=0, verbose_name="Parking Price")),
                (
                    "vehicle_size",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("FOUR-SMALL", "Four-Small"),
                            ("FOUR-LARGE", "Four-Large"),
                        ],
                        default="FOUR-SMALL",
                        max_length=50,
                        verbose_name="Vehicle Size",
                    ),
                ),
                (
                    "has_charging",
                    models.BooleanField(default=False, verbose_name="Has Charging"),
                ),
                (
                    "parking_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_price",
                        to="api.parkingsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Slot Number"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("FOUR-SMALL", "Four-Small"),
                            ("FOUR-LARGE", "Four-Large"),
                        ],
                        default="FOUR-SMALL",
                        max_length=50,
                        verbose_name="Slot Type",
                    ),
                ),
                (
                    "is_charging_available",
                    models.BooleanField(
                        default=False, verbose_name="Is Charging Available"
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Is Booked"),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=False, verbose_name="Is Reserved"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_slot",
                        to="api.parkingsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parking Slot",
            },
        ),
    ]
