# Generated by Django 5.1.4 on 2025-06-11 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_parking_status_parking_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="parking",
        ),
        migrations.AddField(
            model_name="ticket",
            name="parking_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parking_slot_ticket",
                to="api.parkingslot",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Vehicle Number"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("FOUR-SMALL", "Four-Small"),
                            ("FOUR-LARGE", "Four-Large"),
                        ],
                        default="FOUR-SMALL",
                        max_length=50,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "is_electric",
                    models.BooleanField(default=False, verbose_name="Is Electric"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_user_vehicle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle",
            },
        ),
        migrations.CreateModel(
            name="Passes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("price", models.FloatField(default=0, verbose_name="Pass Price")),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_passes",
                        to="api.parking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_user_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_passes",
                        to="api.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Passes",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_ticket",
                to="api.vehicle",
            ),
        ),
    ]
