# Generated by Django 5.1.4 on 2025-06-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_ticket_parking_ticket_parking_slot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.AddField(
            model_name="ticket",
            name="parking_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parking_price_ticket",
                to="api.parkingprice",
            ),
        ),
    ]
