# Generated by Django 5.1.4 on 2025-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_ticket_price_ticket_parking_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="area",
        ),
        migrations.RemoveField(
            model_name="parking",
            name="size",
        ),
        migrations.AddField(
            model_name="parking",
            name="capacity",
            field=models.IntegerField(default=0, verbose_name="Parking Capacity"),
        ),
        migrations.DeleteModel(
            name="Area",
        ),
    ]
